---
version: 12.5.1
slug: samba
name: Samba share
description: 暴露Home Assistant文件夹使用SMB/CIFS。
url: https://gh-proxy.com/github.com/home-assistant/addons/tree/master/samba
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
image: docker.m.daocloud.io/homeassistant/{arch}-addon-samba
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  username: homeassistant
  password: null
  workgroup: WORKGROUP
  local_master: true
  enabled_shares:
    - addons
    - addon_configs
    - backup
    - config
    - media
    - share
    - ssl
  compatibility_mode: false
  apple_compatibility_mode: true
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
schema:
  username: str
  password: password
  workgroup: str
  local_master: bool
  enabled_shares:
    - "match(^(?i:(addons|addon_configs|backup|config|media|share|ssl))$)"
  compatibility_mode: bool
  apple_compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
startup: services
