version: "3.0.0-alpha.80"
image: ghcr.nju.edu.cn/t0bst4r/home-assistant-matter-hub-addon
slug: hamh
name: Home-Assistant-Matter-Hub
description: 从Home Assistant发布您的实体到任何Matter兼容控制器，如Alexa、Apple Home或Google Home。
url: https://gh-proxy.com/github.com/t0bst4r/home-assistant-matter-hub
panel_icon: mdi:hub
panel_title: Matter Hub
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
