name: PlanarAlly
version: "v2025.1.1"
upstream: 2024.3 
slug: planarally
description: 平面盟友是一个开源的虚拟桌面工具（VTT）网络工具，旨在帮助您和您的玩家发现各种虚构的世界。它设计为无需互联网访问即可使用，以适应黑暗地牢，并具有多种功能来增强沉浸感，如照明和视野。
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  8000/tcp: 8000 
ports_description:
  8000/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
boot: manual
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8000]"
ingress: false
ingress_port: 8000