{
  "name": "xiaozhi MCP",
  "version": "v0.0.1",
  "slug": "xiaozhi_mcp",
  "description": "小智AI对接HA MCP",
  "url": "https://www.hasscn.top",
  "arch": [
    "amd64",
    "armhf",
    "armv7",
    "aarch64",
    "i386"
  ],
  "init": false,
  "startup": "services",
  "ingress": true,
  "hassio_api": true,
  "hassio_role": "manager",
  "options": {
    "API_ACCESS_TOKEN": "API_ACCESS_TOKEN",
    "XIAOZHI_MCP_ENDPOINT": "XIAOZHI_MCP_ENDPOINT"
  },
  "schema": {
    "API_ACCESS_TOKEN": "str",
    "XIAOZHI_MCP_ENDPOINT": "str"
  }
}
