---
name: Traefik
version: 4.2.5
slug: traefik
description: Traefik 是一个现代的 HTTP 反向代理和负载均衡器，使部署微服务变得简单。
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying
  microservices easy.
arch:
  - aarch64
  - amd64
  - armv7
image: "ghcr.nju.edu.cn/bluemaex/ha-addons-traefik-{arch}"
startup: system
url: https://ghfast.top/github.com/bluemaex/home-assistant-addons/tree/master/traefik
ports:
  80/tcp: 83
  443/tcp: 443
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
init: false
ingress: true
ingress_entry: dashboard/
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - config
  - share
  - ssl:rw
options:
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  dynamic_configuration_path: "/config/traefik/"
  letsencrypt:
    enabled: false
    resolvers: []
  metrics:
    enabled: true
  env_vars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  pilot_token: str?
  metrics:
    enabled: bool?
  env_vars:
    - str
