name: YT Music PO Token Generator
version: 0.8.5
slug: ytm_po_token_generator
description: 一个用于生成 YouTube 音乐的 PO 令牌的 BgUtils POT 提供程序的 HA 扩展程序包装器。
url: https://ghfast.top/github.com/Brainicism/bgutil-ytdlp-pot-provider
image: brainicism/bgutil-ytdlp-pot-provider
arch:
  - amd64
  - aarch64
ports:
  "4416/tcp": 4416
