{
  "version": "1.0.0",
  "name": "WebTunnel",
  "url": "https://www.hasscn.top",
  "slug": "webtunnel",
  "codenotary": "djhhui@gmail.com",
  "description": "安全好用的内网穿透软件",
  "arch": ["amd64", "aarch64"],
  "startup": "services",

  "init": false,
  "hassio_role": "manager",
  "panel_icon": "mdi:server-network",
  "ports": {
    "9600/tcp": 9600
  },
  "devices": [
    "/dev/net/tun"
  ],
  "boot": "auto",
  "restart": "always",
  "host_network": true,
  "webui": "http://[HOST]:[PORT:9600]"
}

