---
build_from:
  aarch64: ghcr.nju.edu.cn/hassio-addons/base:17.2.5
  amd64: ghcr.nju.edu.cn/hassio-addons/base:17.2.5
  armv7: ghcr.nju.edu.cn/hassio-addons/base:17.2.5
#codenotary:
#  signer: lucio.tarantino@gmail.com
#  base_image: codenotary@frenck.dev
cosign:
#  #base_identity: https://ghfast.top/github.com/home-assistant/builder/.*
  identity: https://ghfast.top/github.com/dianlight/hassio-addons/.*
#args:
  #  HDDTEMP_VERSION: "0.3-beta15"
