build_from:
  armhf: "ghcr.nju.edu.cn/hassio-addons/base:17.2.4"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base:17.2.4"
  aarch64: "ghcr.nju.edu.cn/hassio-addons/base:17.2.4"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base:17.2.4"
  i386: "ghcr.nju.edu.cn/hassio-addons/base:17.2.4"
