build_from:
  armhf: "ghcr.nju.edu.cn/hassio-addons/base-python:16.1.3"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base-python:16.1.3"
  aarch64: "ghcr.nju.edu.cn/hassio-addons/base-python:16.1.3"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base-python:16.1.3"
  i386: "ghcr.nju.edu.cn/hassio-addons/base-python:16.1.3"
