name: "3DPrinter-OctoPrint"
version: "2024.11.0"
slug: "3dprinter-octoprint"
description: "3DPrinter-OctoPrint is a 3D printer management software that allows you to control and monitor your 3D printer from a web interface."
arch:
  - armv7
  - amd64
  - armhf
  - aarch64
url: "https://ghfast.top/github.com/fredrikbaberg/ha-3dprinter-addons/tree/main/3dprinter-octoprint"
webui: http://[HOST]:[PORT:5000]
ports:
  5000/tcp: null
ports_description:
  5000/tcp: Web-based interface
devices:
  - "/dev/i2c-0"
  - "/dev/i2c-1"
gpio: true
usb: true
uart: true
options:
  trusted_proxies: ""
  camera_url: ""
schema:
  trusted_proxies: "str?"
  camera_url: "str?"
image: ghcr.nju.edu.cn/fredrikbaberg/ha-addon-3dprinter-octoprint-{arch}
tmpfs: true
panel_icon: mdi:printer-3d
panel_title: 3DPrinter-OctoPrint
init: false
realtime: true
