name: TasmoAdmin
version: 0.31.5
slug: sonweb
description: 中央管理所有您的Sonoff-Tasmota设备。
url: https://ghfast.top/github.com/hassio-addons/addon-tasmoadmin
codenotary: codenotary@frenck.dev
webui: '[PROTO:ssl]://[HOST]:[PORT:9541]'
startup: system
init: false
arch:
- aarch64
- amd64
- armv7
map:
- ssl
ports:
  9541/tcp: 9541
ports_description:
  9541/tcp: TasmoAdmin web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
image: ghcr.nju.edu.cn/hassio-addons/tasmoadmin/{arch}
