name: wDOSg
version: "v1.3.7"
upstream: latest
slug: wdosg
description: "一个简单的Web服务器，用于管理和运行基于浏览器的DOS游戏。 老王杂谈说"
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  3001/tcp: 3001 
ports_description:
  3001/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
environment:
    DB_PATH: "/config/database"
    GAMES_LIBRARY: "/config/wdosglibrary"   
options:
    TWITCH_CLIENT_ID:
    TWITCH_CLIENT_SECRET:
schema:
    TWITCH_CLIENT_ID: "str"
    TWITCH_CLIENT_SECRET: "str"
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:3001]"
ingress: false
ingress_port: 3001
