---
name: TorrServer
slug: torrserver
description: TorrServer for home assistant 翻译为中文是“家庭助手Torrs服务器”。
image: ghcr.nju.edu.cn/aatrubilin/hassio-torrserver/{arch}
version: 1.3.1-MatriX.135
url: https://ghfast.top/github.com/aatrubilin/hassio-torrserver
codenotary: aatrubilin@gmail.com
init: false
auth_api: true
arch:
  - armv7
  - armhf
  - amd64
  - i386
  - aarch64
map:
  - addon_config:rw
options:
  httpauth: false
  logins:
    - username: homeassistant
      password: homeassistant
  tgtoken: ""
  m3u_custom_host: ""
schema:
  httpauth: bool
  logins:
    - username: str
      password: password
  tgtoken: "str?"
  m3u_custom_host: "str?"
ingress: true
ingress_port: 8090
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: TorrServer port
startup: system
panel_icon: mdi:movie
