name: Music Assistant Server (beta)
version: 2.6.0b4
slug: music_assistant_beta
description: $'音乐助理的beta版本。如果您想跟上最新的功能并愿意进行一些beta测试，请安装此版本！在Discord上关注我们以报告和讨论反馈！

（注：由于“Music Assistant”可能指代多个不同的软件或项目，因此无法确定具体是哪一个。如果需要更具体的翻译，请提供更多信息。）'
  keep up with the latest and greatest and don't mind some beta testing. Follow us
  on discord to report and discuss feedback!
url: https://music-assistant.io
arch:
- amd64
- aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
- media:rw
init: false
advanced: false
backup_exclude:
- cache.db
- collage_images/*
- .cache/*
stage: stable
image: ghcr.nju.edu.cn/music-assistant/server
tmpfs: true
options:
  log_level: info
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  safe_mode: bool
privileged:
- SYS_ADMIN
- DAC_READ_SEARCH
