name: pigpio
version: 1.5.3
slug: pigpio
description: 用pigpio在Home Assistant上控制PWM LED。
url: https://ghfast.top/github.com/Poeschl-HomeAssistant-Addons/pigpio
arch:
- armhf
- armv7
- aarch64
startup: services
gpio: true
privileged:
- SYS_RAWIO
devices:
- /dev/mem
- /dev/vcio
image: ghcr.nju.edu.cn/poeschl-homeassistant-addons/pigpio-{arch}
init: false
ports:
  8888/tcp: 8888
ports_description:
  8888/tcp: The port to control pigpio
schema:
  additional_options: str?
