---
build_from:
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base-debian:bullseye
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base-debian:bullseye
#codenotary:
#  signer: notary@home-assistant.io
#  base_image: notary@home-assistant.io
#args:
#  WYOMING_WHISPER_VERSION: 2.4.0
