name: Caddy 2
version: 2.0.3
slug: caddy-2
description: 开源的Web和代理服务器，具有自动HTTPS功能。 老王杂谈说
url: https://gh-proxy.com/github.com/einschmidt/addon-caddy-2
arch:
- armhf
- armv7
- amd64
- aarch64
startup: services
map:
- type: share
  read_only: false
- type: addon_config
  read_only: false
- type: ssl
  read_only: false
host_network: true
options:
  non_caddyfile_config:
    email: your@email.com
    domain: mydomain.com
    destination: localhost
    port: 8123
  args: []
  env_vars: []
  log_level: info
schema:
  non_caddyfile_config:
    email: email?
    domain: str?
    destination: str?
    port: port?
  caddy_upgrade: bool?
  caddy_fmt: bool?
  args:
  - str
  env_vars:
  - name: str
    value: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
environment:
  LOG_FORMAT: '{LEVEL}: {MESSAGE}'
init: false
breaking_versions:
- 2.0.0
image: ghcr.nju.edu.cn/einschmidt/caddy-2/{arch}
