---
#  https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.nju.edu.cn/home-assistant/aarch64-base:3.21"
  armhf: "ghcr.nju.edu.cn/home-assistant/armhf-base:3.21"
  armv7: "ghcr.nju.edu.cn/home-assistant/armv7-base:3.21"
  amd64: "ghcr.nju.edu.cn/home-assistant/amd64-base:3.21"
  #  i386: "ghcr.nju.edu.cn/home-assistant/i386-base:3.16"

labels:
  org.opencontainers.image.title: "SBFspot for Home Assistant"
  org.opencontainers.image.description: "SBFspot for new add-ons."
  org.opencontainers.image.source: "https://ghfast.top/github.com/habuild"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  base_image: notary@home-assistant.io
args:
  TEMPIO_VERSION: "2021.09.0"
