name: MyIP
version: "v5.0.1"
upstream: latest
slug: myip
description: 最好的IP工具箱。轻松检查您的IP地址、IP地理位置、检测DNS泄露、检查WebRTC连接、速度测试、ping测试、MTR测试、检查网站可用性、whois搜索等！
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  18966/tcp: 18966 
ports_description:
  18966/tcp: "Web Interface"
image: ghcr.nju.edu.cn/jason5ng32/myip
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:18966]"
ingress: false
ingress_port: 18966 
