build_from:
  armhf: "ghcr.nju.edu.cn/hassio-addons/base:17.2.2"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base:17.2.2"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base:17.2.2"
  i386: "ghcr.nju.edu.cn/hassio-addons/base:17.2.2"
