name: Signal Messenger
url: https://ghfast.top/github.com/haberda/signal-addon/tree/master/
version: 0.92.0
slug: signal_messenger
arch:
- aarch64
- amd64
- armv7
description: 信号消息主控中心附加组件
startup: services
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Rest-api port
options:
  mode: list(normal|native|json-rpc)
  AUTO_RECEIVE: true
  SIGNAL_CLI_CMD_TIMEOUT: 60
map:
- addon_config:rw
schema:
  mode: list(normal|native|json-rpc)
  AUTO_RECEIVE: bool
  SIGNAL_CLI_CMD_TIMEOUT: int
environment:
  SIGNAL_CLI_CONFIG_DIR: /config
image: ghcr.nju.edu.cn/haberda/signal_messenger/{arch}
