name: "LiveBook"
version: "0.16.0"
upstream: "0.16.0"
slug: livebook
description: Livebook 是一个用于编写交互式和协作代码笔记本的 Web 应用。
  Livebook is a web application for writing interactive and collaborative code notebooks
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web Interface"
image: ghcr.nju.edu.cn/livebook-dev/livebook
map:
  - type: addon_config
    read_only: false
environment:
  LIVEBOOK_DATA_PATH: "/config/"
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
ingress: false
ingress_port: 8080
